# Generated by Django 4.2.7 on 2024-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=7, verbose_name='Цена'),
        ),
    ]
