# Generated by Django 4.2.7 on 2024-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_photoforphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phones_detail', verbose_name='Изображение4'),
        ),
    ]
