# Generated by Django 4.2.7 on 2024-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_photoforphone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='phones_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='phones_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='phones_images', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='PhotoForPhone',
        ),
    ]
